version: "3.9"  # optional since v1.27.0

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - .:/var/www/codebase
    ports:
      - 82:80
    networks:
      - mytheresa

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'mytheresa_assignment'
      #  MYSQL_USER: 'app'
      #  MYSQL_PASSWORD: 'abcd1234'
    #volumes:
    # - ./docker/mysql:/var/lib/mysql
    networks:
     - mytheresa

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        TIMEZONE: 'UTC'
    volumes:
      - .:/var/www/codebase
    networks:
      - mytheresa

  redis:
    image: redis:alpine
    networks:
      - mytheresa



networks:
  mytheresa:
    name: mytheresa
