# Coddict Docker Boilerplate Version 2.1
FROM nginx:mainline-alpine

COPY docker/nginx/nginx.conf  /etc/nginx/
COPY docker/nginx/default.conf /etc/nginx/conf.d/
RUN echo "upstream php-upstream { server php:9000; }" > /etc/nginx/conf.d/upstream.conf

EXPOSE 82
EXPOSE 443
